### ISSUE TITLE
Texture CD images?

### ISSUE THREAD

**Issue by BlinksTale** [GhostlyDark/OoT-Reloaded#16]
Nintendo often used textures in OoT from premade texture CDs. The n64 exports were low res, but the CDs themselves had higher resolutions. Can you add to the README whether these are from those CDs, or if not, the basis of the upscales? There are purists interested in texture packs from those CDs, and it helps gauge trust for the download and installation if the basis of the pack is more clear.

**Comment by GhostlyDark** [comment]
Out of thousands of textures, there are just a few based on source textures. The Deku Shield backside, grayscaled brick wall in Gerudo Training Ground and a grayscaled brick wall in the Guardhouse come to mind - the shield backside very much edited to look less noisy. The Render96 Wiki has details on where these come from.

Most textures of the pack aren't upscaled and the low resolution ones that are exist because even to this day, no better assets have been made. I have no idea where the notion comes from that Reloaded is merely an AI upscaled pack. Upscaling is a tool to create and or improve textures, not something that can be blindly used to batch upscale all textures of an entire game. Even Nerrel used AI upscaling on his own textures for a pack that primarily consists of hand drawn textures.

**Comment by BlinksTale** [comment]
Of course - I’m just saying that this information isn’t in the readme. Maybe you can say that there, or link the wiki from the readme? When I look for texture packs I want to know how close it is to the source (many have drastic art direction changes that I dislike, eg. All the colors are different). Explaining the methodology behind the upscaling and the technique or balance between hand made and AI would be great

**Comment by GhostlyDark** [comment]
The website has more info on what fonts where used to recreate the text among what other packs it borrows the assets from. Ideally HD textures are as close to the original as possible - same color and everything. It's usually the textures that deviate from the original that need replacement the most.

It's a fair point that I should expand on that info, so I'll put in the effort for that.
